### ISSUE TITLE
Compatibility with joined-table inheritance

### ISSUE THREAD

**Issue by mush42** [uralbash/sqlalchemy_mptt#62]
Currently sqlalchemy-mptt tries to set table indexes in the **__table_args__** class method. This make sqlalchemy complains when it tries to construct child classes because it couldn't find columns declared in the base class.
I fixed this in my local setup by adding **index=True** to column definition, instead of defining indexs in a separate class method.

Should I create a PR to fix this?

**Comment by uralbash** [comment]
@mush42 Yes sure it would be great if you add it

**Comment by snitkoff** [comment]
@uralbash It would be great if you paid attention to this request #63

**Comment by uralbash** [comment]
@snitkoff @mush42 Sorry for the wait, I merge your changes
