### ISSUE TITLE
Feature Request: Implement Child and sibling methods

### ISSUE THREAD

**Issue by AlexZettler** [uralbash/sqlalchemy_mptt#64]
Coming from django_mptt, I miss the feature of being able to retrieve simply the children/siblings of the node. Both of these features are tightly linked as the siblings of a node are it's parent's children. I am working with a hierarchy of pages and want the user to only see a layer down from the current node. Although it is possible to write methods to filter out a drilldown tree I suspect that there is a more efficient way of preforming this operation.

I am really glad that this plugin exists for flask and would love to help in any way that I can.

**Comment by uralbash** [comment]
Could you give a link to django-mptt documentation where these functions are described I think it's not so hard to add

**Comment by AlexZettler** [comment]
Certainly! here are links to the documentation and the implementation source. 

**[get_siblings documentation](https://django-mptt.readthedocs.io/en/latest/models.html#get-siblings-include-self-false)**
[get_siblings definition](https://github.com/django-mptt/django-mptt/blob/fd76a816e05feb5fb0fc23126d33e514460a0ead/mptt/models.py#L704)

**[get_children documentation](https://django-mptt.readthedocs.io/en/latest/models.html#get-children)**
[get_children definition](https://github.com/django-mptt/django-mptt/blob/fd76a816e05feb5fb0fc23126d33e514460a0ead/mptt/models.py#L563)

**Comment by uralbash** [comment]
You can do this with simple queries, I'm not sure that it is correct to separate them into a separate method
 
> **[get_siblings documentation](https://django-mptt.readthedocs.io/en/latest/models.html#get-siblings-include-self-false)**
> [get_siblings definition](https://github.com/django-mptt/django-mptt/blob/fd76a816e05feb5fb0fc23126d33e514460a0ead/mptt/models.py#L704)

`items = session.query(Tree).filter(Tree.parent_id == node.parent_id).all()`

> **[get_children documentation](https://django-mptt.readthedocs.io/en/latest/models.html#get-children)**
> [get_children definition](https://github.com/django-mptt/django-mptt/blob/fd76a816e05feb5fb0fc23126d33e514460a0ead/mptt/models.py#L563)

`items = session.query(Tree).filter(Tree.parent_id == node.id).all()`

**Comment by AlexZettler** [comment]
That's a really easy way to get that data. I'm still getting into SQAlchemy. I love readable code (hence my love for python) and will extend the class functionality for my project regardless. I would suggest implementing these methods for ease of development even if they are simple queries.

**Comment by uralbash** [comment]
@AlexZettler 
You can use it in new `0.2.5` version of `sqlalchemy_mptt`
See examples:
https://github.com/uralbash/sqlalchemy_mptt/blob/master/sqlalchemy_mptt/tests/cases/get_node.py
